name: Sconify

on:
  workflow_dispatch:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      debug-only:
        type: boolean
        default: true

jobs:
  sconify:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/sconify.yml@feat/sconify
    with:
      image-name: ${{inputs.image-name}}
      image-tag: ${{inputs.image-tag}}
      debug-only: ${{inputs.debug-only}}
      docker-registry: "docker.io"
      sconify-version: "5.9.0-v15"
      fs-dir: "/app"
      binary: "/usr/local/bin/node"
      command: "node /app/src/app.js"
      heap: "1G"
      dlopen: 1
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-password: ${{ secrets.DOCKER_TOKEN }}
      scontain-username: ${{ secrets.SCONTAIN_USERNAME }}
      scontain-password: ${{ secrets.SCONETAIN_TOKEN }}
      scone-signing-key: ${{ secrets.SCONE_SIGNING_KEY }}
