name: Sconify

on:
  workflow_dispatch:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      sconify-debug:
        type: boolean
        default: true
      sconify-prod:
        type: boolean
        default: true

jobs:
  sconify:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/sconify.yml@feat/sconify
    with:
      image-name: ${{ inputs.image-name }}
      image-tag: ${{ inputs.image-tag }}
      sconify-debug: ${{ inputs.sconify-debug }}
      sconify-prod: ${{ inputs.sconify-prod }}
      docker-registry: docker.io
      sconify-version: 5.9.0-v15
      fs-dir: /app
      binary: /usr/local/bin/node
      command: node /app/src/app.js
      heap: 1G
      dlopen: 1
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-password: ${{ secrets.DOCKER_TOKEN }}
      scontain-username: ${{ secrets.SCONTAIN_USERNAME }}
      scontain-password: ${{ secrets.SCONETAIN_TOKEN }}
      scone-signing-key: ${{ secrets.SCONE_SIGNING_KEY }}

  print-out:
    runs-on: ubuntu-latest
    needs: sconify
    steps:
      - env:
          DEBUG_IMAGE: ${{ needs.sconify.outputs.debug-image }}
          DEBUG_CHECKSUM: ${{ needs.sconify.outputs.debug-checksum }}
          DEBUG_MRENCLAVE: ${{ needs.sconify.outputs.debug-mrenclave }}
          PROD_IMAGE: ${{ needs.sconify.outputs.prod-image }}
          PROD_CHECKSUM: ${{ needs.sconify.outputs.prod-checksum }}
          PROD_MRENCLAVE: ${{ needs.sconify.outputs.prod-mrenclave }}
        run: |
          echo "DEBUG IMAGE INFO: image=$DEBUG_IMAGE | checksum=$DEBUG_CHECKSUM | mrenclave=$DEBUG_MRENCLAVE"
          echo "PROD IMAGE INFO: image=$PROD_IMAGE | checksum=$PROD_CHECKSUM | mrenclave=$PROD_MRENCLAVE"
