name: with environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to use"
        required: true

jobs:
  check-environment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: echo FOO
        uses: ./.github/workflows/reusable-echo.yml
        with:
          msg: ${{ vars.FOO }}
